spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

      routes:
        # ✅ REST API 요청용
        - id: task-service-api
          uri: http://task-service:8080
          predicates:
            - Path=/api/task/**
          filters:
            - StripPrefix=1

        # ✅ WebSocket 요청용
        - id: task-service-ws
          uri: http://task-service:8080
          predicates:
            - Path=/api/ws-progress
          filters:
            - StripPrefix=1

        - id: grading-service
          uri: http://grading-service:8080
          predicates:
            - Path=/api/grading/**
          filters:
            - StripPrefix=1

        - id: user-info-service
          uri: http://user-info-server:9004
          predicates:
            - Path=/api/user-info/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG

springdoc:
  swagger-ui:
    urls:
      - name: GRADING-SERVER
        url: http://localhost:9002/v3/api-docs
      - name: LEADERBOARD-SERVER
        url: http://localhost:9003/v3/api-docs
      - name: USER-SERVER
        url: http://localhost:9004/v3/api-docs

jwt:
  secret: "dF2j8Qx1Vp9!tBrS4l7Ae6Zp3Yw0LmCiOkJrHuZw9@GqVt5NcXh8PuLa2MqDnRoWcSvXbUcZyQnFgLkJt9EzRkBvWaXcYsUqNmTlPoHrGeDbFhQk"
